version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: papermark-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-papermark}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-papermark}
      POSTGRES_DB: ${POSTGRES_DB:-papermark}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-papermark}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: papermark-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-25256}:3000"
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-papermark}:${POSTGRES_PASSWORD:-papermark}@postgres:5432/${POSTGRES_DB:-papermark}?schema=public
      POSTGRES_PRISMA_URL: postgresql://${POSTGRES_USER:-papermark}:${POSTGRES_PASSWORD:-papermark}@postgres:5432/${POSTGRES_DB:-papermark}?schema=public
      POSTGRES_PRISMA_URL_NON_POOLING: postgresql://${POSTGRES_USER:-papermark}:${POSTGRES_PASSWORD:-papermark}@postgres:5432/${POSTGRES_DB:-papermark}?schema=public
      
      # Application
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:25256}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL:-http://localhost:25256}
      
      # Storage
      STORAGE_PROVIDER: ${STORAGE_PROVIDER:-vercel-blob}
      BLOB_READ_WRITE_TOKEN: ${BLOB_READ_WRITE_TOKEN}
      NEXT_PUBLIC_VERCEL_BLOB_BASE_URL: ${NEXT_PUBLIC_VERCEL_BLOB_BASE_URL}
      
      # AWS S3 (if using S3 storage)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_REGION: ${AWS_S3_REGION}
      
      # Email
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_AUDIENCE_ID: ${RESEND_AUDIENCE_ID}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@localhost}
      
      # Analytics
      TINYBIRD_TOKEN: ${TINYBIRD_TOKEN}
      NEXT_PUBLIC_TINYBIRD_BASE_URL: ${NEXT_PUBLIC_TINYBIRD_BASE_URL:-https://api.tinybird.co}
      
      # Authentication
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      
      # Stripe
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      
      # Upstash
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      UPSTASH_QSTASH_URL: ${UPSTASH_QSTASH_URL}
      UPSTASH_QSTASH_TOKEN: ${UPSTASH_QSTASH_TOKEN}
      
      # Security
      DOCUMENT_ENCRYPTION_KEY: ${DOCUMENT_ENCRYPTION_KEY}
      
      # Trigger.dev
      TRIGGER_SECRET_KEY: ${TRIGGER_SECRET_KEY}
      TRIGGER_API_URL: ${TRIGGER_API_URL}
      
      # Hanko
      HANKO_API_KEY: ${HANKO_API_KEY}
      NEXT_PUBLIC_HANKO_TENANT_ID: ${NEXT_PUBLIC_HANKO_TENANT_ID}
      
      # Node
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app_uploads:/app/uploads

volumes:
  postgres_data:
  app_uploads: